### ISSUE TITLE
'Read-only application cannot POST.' error message 

### ISSUE THREAD

**Issue by stanjdev** [fourtonfish/random-image-twitterbot#6]
HI fourtonfish, 

I have cloned your project, only changed the console.js file like you said, i haven't added and photos or changed anything else. but when I run it in terminal using 'node server.js', I get this error. what am I doing wrong? 

```
Opening an image...
Uploading an image...
ERROR:
Error: Read-only application cannot POST.
    at Object.exports.makeTwitError (/Users/stanleyjeong/Desktop/_CODING/twitter-bots/bot-take4-fourtonfish-github/random-image-twitterbot/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/Users/stanleyjeong/Desktop/_CODING/twitter-bots/bot-take4-fourtonfish-github/random-image-twitterbot/node_modules/twit/lib/twitter.js:344:25)
    at Request.<anonymous> (/Users/stanleyjeong/Desktop/_CODING/twitter-bots/bot-take4-fourtonfish-github/random-image-twitterbot/node_modules/twit/lib/twitter.js:364:7)
    at Request.emit (events.js:327:22)
    at Gunzip.<anonymous> (/Users/stanleyjeong/Desktop/_CODING/twitter-bots/bot-take4-fourtonfish-github/random-image-twitterbot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'Read-only application cannot POST.',
  code: null,
  allErrors: [
    {
      request: '/1.1/media/upload.json',
      error: 'Read-only application cannot POST.'
    }
  ],
  twitterReply: {
    request: '/1.1/media/upload.json',
    error: 'Read-only application cannot POST.'
  },
  statusCode: 401
}
```

thank you for your help!

**Comment by stefanbohacek** [comment]
Can you check your app's permissions? See https://botwiki.org/resource/tutorial/how-to-create-a-twitter-app/#permissions

**Comment by stanjdev** [comment]
Awesome, it worked! I regenerated the access tokens once I switched the permissions on my project. thank you!

![Screen Shot 2020-04-06 at 11 26 57 AM](https://user-images.githubusercontent.com/61481150/78592573-271d9180-77fa-11ea-95d1-c42c24f5af0f.png)

Is there a way to not have it post from my personal twitter account? Or do I have to make a new twitter account and apply for a new developer account along with it? 

thanks for the help!

**Comment by stefanbohacek** [comment]
Sure, no problem!

I usually set up a new account for each bot and apply for developer account with it.

You could also use one developer account, create multiple apps, and separate Twitter accounts for your bots, and then [authenticate those bot accounts](https://developer.twitter.com/en/docs/basics/authentication/oauth-1-0a/obtaining-user-access-tokens), but the first option seems simpler.

**Comment by stanjdev** [comment]
Thank you, Stefan, you have been so very helpful!!

**Comment by stefanbohacek** [comment]
Sure, no problem!
